### ISSUE TITLE
Field Layout is dropped when Installing

### ISSUE THREAD

**Issue by jbutts-nerdery** [fortrabbit/craft-object-storage#4]
Hello!

When installing the v1.0.3.1 of fortrabbit Object Storage Volume on Craft 3.3.17, the Asset volumes convert from "Amazon S3" to "fortrabbit Object Storage" as expected, but the field layout options get reset. The data still exists, so I'm wondering if this could be reconnected during the afterInstall event within the plugin.

Thanks for your consideration!

**Comment by ostark** [comment]
> from "Amazon S3" to "fortrabbit Object Storage" as expected

Did you upgrade from Craft 2 to 3?

---

Can you tell me what "field layout options" are? What is the expected and what's the actual state?

**Comment by jbutts-nerdery** [comment]
Yes, we are upgrading from 2 to 3, but the disconnect seems to happen specifically when installing the plugin with volumes.php configurations matching existing S3 buckets. Field layout options are the assigned fields for each Asset Volume. I'm attaching screenshots of the expected and actual states. This view occurs after selecting a volume from _/admin/settings/assets_

**Expected/Pre-install**
![expected](https://user-images.githubusercontent.com/3858032/70631854-6d1f6b80-1bf3-11ea-9fe0-4fd8b44eaa80.png)

**Actual/Post-install**
![actual](https://user-images.githubusercontent.com/3858032/70631913-845e5900-1bf3-11ea-8ea4-eca538a92328.png)

Thanks Oli!

**Comment by ostark** [comment]
I see - in Craft2 the `assetsources.type` (volumes assetsources, type field) was `S3`.
Those are migrated to `volumes.type` craft\awss3\Volume  - right?

The new `volumes.type`  for the Object Storage is `fortrabbit\ObjectStorage\Volume`.
As the `volumes.handle` is not unique an automate migration is not possible.

Manually changing the ids would work, but it is a bit hacky. A proper migration would be good, right?
Since the fields and values are just assumptions, it would be good to see the contents of the volumes table. Feel free to use our support chat to share it and reference this issue.

**Comment by jbutts-nerdery** [comment]
Thanks Oli! I'll reach out in the support chat.

**Comment by jbutts-nerdery** [comment]
Resolved in 1.1.0, thank you!
